// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBkXeLH2edKXQIOj-MsGWbTSer8gvQ2s',
    appId: '1:303132568732:web:7d15f45c83d60a85ff1159',
    messagingSenderId: '303132568732',
    projectId: 'fusionfesta',
    authDomain: 'fusionfesta.firebaseapp.com',
    storageBucket: 'fusionfesta.firebasestorage.app',
    measurementId: 'G-C9D10ZR2WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsFQCpmNH75ska9RhBwape8lggAXI6EA8',
    appId: '1:303132568732:android:3c7bcef1c7361e90ff1159',
    messagingSenderId: '303132568732',
    projectId: 'fusionfesta',
    storageBucket: 'fusionfesta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9pu3scsa5AQylLnRJkkuWGn6PU52Ywu4',
    appId: '1:303132568732:ios:459a8cbca21276fdff1159',
    messagingSenderId: '303132568732',
    projectId: 'fusionfesta',
    storageBucket: 'fusionfesta.firebasestorage.app',
    iosBundleId: 'com.example.fusionFesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9pu3scsa5AQylLnRJkkuWGn6PU52Ywu4',
    appId: '1:303132568732:ios:459a8cbca21276fdff1159',
    messagingSenderId: '303132568732',
    projectId: 'fusionfesta',
    storageBucket: 'fusionfesta.firebasestorage.app',
    iosBundleId: 'com.example.fusionFesta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsBkXeLH2edKXQIOj-MsGWbTSer8gvQ2s',
    appId: '1:303132568732:web:bda96a97bc1d71e8ff1159',
    messagingSenderId: '303132568732',
    projectId: 'fusionfesta',
    authDomain: 'fusionfesta.firebaseapp.com',
    storageBucket: 'fusionfesta.firebasestorage.app',
    measurementId: 'G-BS0VQ28F5E',
  );
}
